"""Example sandbox environment server generated by `orwd init`."""
from openreward.environments import Server

# from sandbox_env import SandboxEnv
from accountant_env import AccountantEnv

if __name__ == "__main__":
    server = Server([AccountantEnv])
    server.run()
